name: PyPlugins
main: me.kapehh.net.pyplugins.Main
author: kapehh
version: 2.0.0
description: "Develop features on Python [by kapehh]"
commands:
  pyplugins:
    aliases: [pyp]
    description: "Manage PyPlugins"
    usage: |
      /<command> - list loaded PyPlugin's
      /<command> load <PyPluginName> - load PyPlugin
      /<command> reload <PyPluginName> - reload PyPlugin
      /<command> unload <PyPluginName> - unload PyPlugin
      /<command> thread-list - list of thread in group 'jython-threads'
      /<command> thread-stop <ThreadName> - interrupt thread
  pycommand:
    aliases: [pyc]
    description: "PyPlugin commands"
    usage: "Usage: /<command> <cmd> [args]"